### ISSUE TITLE
Restrict OriginPatterns

### ISSUE THREAD

**Issue by linusseelinger** [ViviLearns2Code/the-game#18]
Only allow frontend's OriginPattern, disable origin pattern checking only for local testing.

For testing, possibly use ` InsecureSkipVerify bool`. See https://godoc.org/nhooyr.io/websocket

**Comment by ViviLearns2Code** [comment]
allowed originPattern now configurable via env variable

**Comment by ViviLearns2Code** [comment]
Allowed originPattern now configurable via env variable
