### ISSUE TITLE
Clean up error message cleanup

### ISSUE THREAD

**Issue by linusseelinger** [ViviLearns2Code/the-game#27]
After triggering an error by sending a bad action type, following correct actions still receive an errorMsg.

How to reproduce:
Start game w/ 2 players
In concentration phase: Click play card. You receive a "errorMsg":"[warning] wrong action:  game is in concentrating, ready action is expected"
Then proceed with valid actions. Those also receive a "errorMsg":"[warning] wrong action:  game is in concentrating, ready action is expected".

**Comment by ViviLearns2Code** [comment]
Reset gameState.err in updateEventsAfterProcessedEvent
